#!/usr/bin/env bash

B="\e[1;34m"
Y="\e[1;33m"
N="\e[0m"
R="\e[1;31m"

#echo -e "[${B}INF${N}] MESSAGE"
#echo -e "[${Y}WAR${N}] WARNING"
#echo -e "[${R}ERR${N}] ERROR"

PRINT() {

  echo -e "[${B}INF${N}] $1"

}

COMPONENT=$1

if [[-z "$COMPONENT"]]; then

INSTALL_COMPONENET="MONGODB MYSWL REDIS RABBITMQ FRONTEND CART CATALOGUE USERPAYMENT SHIPPING RATINGS DISPATCH"

else

case $(COMPONENT) in
    MONGODB|MYSWL|REDIS|RABBITMQ|FRONTEND|CART|CATALOGUE|USERPAYMENT|SHIPPING|RATINGS|DISPATCH
    INSTALL_COMPONENT-${COMPONENT}
    ;;
    *)
    ERROR "INVALID ARGUMENT"
    ;;
esac

for component in $(COMPONENTS) ; do
    PRINT "SETUP ${COMPONENT}"
Done

